version: '3'
services:
  teamcity-server:
    image: jetbrains/teamcity-server
    container_name: teamcity-server
    ports: 
      - "8111:8111"
    environment:
      - TEAMCITY_SERVER_MEM_OPTS=-Xmx1g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m
    volumes:
      - ./tmp/server/datadir:/data/teamcity_server/datadir
      - ./tmp/server/logs:/opt/teamcity/logs
    expose:
      - "8111"
  teamcity-agent:
    image: jetbrains/teamcity-agent
    container_name: teamcity-agent
    environment:
     - SERVER_URL=http://127.0.0.1:8111
    volumes:
     - ./tmp/agent/conf:/data/teamcity_agent/conf
